# Generated by Django 5.0.6 on 2024-06-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=9)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
